apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: infinity-datasource
    access: proxy
    isDefault: false
    jsonData: {}
    version: 1
    editable: true
